version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test