version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
  deploy:
    docker:
       - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run: eb init
      - run: eb deploy Storebackendapi-prod          
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build