version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build